/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    String path = "./src/main/resources/testFile.json";

    @Test
    public void testReadFromFile()
    {
        try
        {
            assertEquals("Method should return the targeted quote and author from the test file.",
                    " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” Marilyn Monroe",
                    Quotes.readFromFile(path));
        } catch (Exception error)
        {
            fail();
        }
    }
}
